/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package impuestovehicular;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author harry
 */
public class InterfazPrincipal extends javax.swing.JFrame {

    private ArrayList<Automovil> listaCarros;
    private  ItemListener il;
    Locale locale = new Locale("es", "ES");
    NumberFormat objNF2 = NumberFormat.getInstance(locale);
    /**
     * Creates new form InterfazPrincipal
     */
    public InterfazPrincipal() throws FileNotFoundException, IOException {
        initComponents();
        colocarInformacion();
        rellenarLinea();
        rellenarAnio();
        rellenarPrecio();
        setLocationRelativeTo(null);
        jScrollPane1.setAutoscrolls(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtextAreaRecibo = new javax.swing.JTextArea();
        botonGenerarRecibo = new javax.swing.JButton();
        jcomboLinea = new javax.swing.JComboBox<>();
        jcomboMarca = new javax.swing.JComboBox<>();
        jcomboAnio = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtextPrecio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtextDescuento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jcheckboxProntoPago = new javax.swing.JCheckBox();
        jcheckboxServicioPublico = new javax.swing.JCheckBox();
        jcheckboxCambioCuenta = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(jLabel1.getForeground());

        jtextAreaRecibo.setEditable(false);
        jtextAreaRecibo.setColumns(20);
        jtextAreaRecibo.setFont(new java.awt.Font("Segoe UI Symbol", 1, 16)); // NOI18N
        jtextAreaRecibo.setRows(5);
        jtextAreaRecibo.setAutoscrolls(false);
        jScrollPane1.setViewportView(jtextAreaRecibo);
        jtextAreaRecibo.getAccessibleContext().setAccessibleParent(null);

        botonGenerarRecibo.setFont(jLabel1.getFont());
        botonGenerarRecibo.setText("Generar Recibo");
        botonGenerarRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGenerarReciboActionPerformed(evt);
            }
        });

        jcomboLinea.setFont(jLabel1.getFont());
        jcomboLinea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));

        jcomboMarca.setFont(jLabel1.getFont());
        jcomboMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        jcomboAnio.setFont(jLabel1.getFont());

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Marca");

        jLabel2.setFont(jLabel1.getFont());
        jLabel2.setForeground(jLabel1.getForeground());
        jLabel2.setText("Linea");

        jLabel3.setFont(jLabel1.getFont());
        jLabel3.setForeground(jLabel1.getForeground());
        jLabel3.setText("Año");

        jtextPrecio.setEditable(false);
        jtextPrecio.setFont(jLabel1.getFont());

        jLabel4.setFont(jLabel1.getFont());
        jLabel4.setForeground(jLabel1.getForeground());
        jLabel4.setText("Descuento");

        jtextDescuento.setEditable(false);
        jtextDescuento.setFont(jLabel1.getFont());

        jLabel5.setFont(jLabel1.getFont());
        jLabel5.setForeground(jLabel1.getForeground());
        jLabel5.setText("Tipo de Descuento:");

        jcheckboxProntoPago.setBackground(new java.awt.Color(255, 255, 255));
        jcheckboxProntoPago.setFont(jLabel1.getFont());
        jcheckboxProntoPago.setForeground(new java.awt.Color(0, 0, 0));
        jcheckboxProntoPago.setText("Pronto Pago");
        jcheckboxProntoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcheckboxProntoPagoActionPerformed(evt);
            }
        });

        jcheckboxServicioPublico.setBackground(new java.awt.Color(255, 255, 255));
        jcheckboxServicioPublico.setFont(jLabel1.getFont());
        jcheckboxServicioPublico.setForeground(new java.awt.Color(0, 0, 0));
        jcheckboxServicioPublico.setText("Servicio Publico");

        jcheckboxCambioCuenta.setBackground(new java.awt.Color(255, 255, 255));
        jcheckboxCambioCuenta.setFont(jLabel1.getFont());
        jcheckboxCambioCuenta.setForeground(new java.awt.Color(0, 0, 0));
        jcheckboxCambioCuenta.setText("Translado de cuenta");

        jLabel6.setFont(jLabel1.getFont());
        jLabel6.setForeground(jLabel1.getForeground());
        jLabel6.setText("Precio");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(27, 27, 27)
                        .addComponent(jtextDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonGenerarRecibo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1)
                                    .addComponent(jcomboMarca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jcheckboxProntoPago)
                                        .addGap(31, 31, 31)
                                        .addComponent(jcheckboxServicioPublico))
                                    .addComponent(jLabel2)
                                    .addComponent(jcomboLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcomboAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jtextPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jcheckboxCambioCuenta)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcomboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcomboLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtextPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcomboAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcheckboxProntoPago)
                    .addComponent(jcheckboxServicioPublico)
                    .addComponent(jcheckboxCambioCuenta))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtextDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(botonGenerarRecibo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcheckboxProntoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcheckboxProntoPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcheckboxProntoPagoActionPerformed

    private void botonGenerarReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGenerarReciboActionPerformed
        String cadena = jtextPrecio.getText().substring(2);
        String numero = "";
        for(int i = 0; i < jtextPrecio.getText().length() -2; i++) {
            if(!cadena.substring(i, i+1).equals("."))
            numero += cadena.substring(i, i+1);
        }
        cadena = numero;
        int precioInicial = Integer.parseInt(cadena);
         String texto = "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"
                + "~\n"
                + "~  Precio del Vehiculo: $ " + objNF2.format(precioInicial) + "\n~\n";
        if (jcheckboxProntoPago.isSelected()) {
            double descuento = 0.10;
            int precio = precioInicial;
            int descontar = (int) (precio * descuento);
            
            texto += "~  Descuento Pronto Pago: $ " + objNF2.format(descontar ) + "\n";
            int precioFinal = precio - descontar;
            precioInicial = precioFinal;

        }
        if (jcheckboxServicioPublico.isSelected()) {
            double descuento = 0.10;
            int precio = precioInicial;
            int descontar = (int) (precio * descuento);
            texto += "~  Descuento Servicio Publico: $ " + objNF2.format(descontar ) + "\n";
            int precioFinal = precio - descontar;
            precioInicial = precioFinal;
        }
        if (jcheckboxCambioCuenta.isSelected()) {
            double descuento = 0.20;
            int precio = precioInicial;
            int descontar = (int) (precio * descuento);
            texto += "~  Descuento Cambio de Cuenta: $ " + objNF2.format(descontar ) + "\n";
            int precioFinal = precio - descontar;
            precioInicial = precioFinal;
        }

        jtextDescuento.setText("$ " + objNF2.format(precioInicial));
        texto += "~\n~  Precio con descuento: $ " + objNF2.format(precioInicial)
                + "~\n~\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~";
        
        jtextAreaRecibo.setText(texto);
    }//GEN-LAST:event_botonGenerarReciboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InterfazPrincipal().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(InterfazPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(InterfazPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGenerarRecibo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jcheckboxCambioCuenta;
    private javax.swing.JCheckBox jcheckboxProntoPago;
    private javax.swing.JCheckBox jcheckboxServicioPublico;
    private javax.swing.JComboBox<String> jcomboAnio;
    private javax.swing.JComboBox<String> jcomboLinea;
    private javax.swing.JComboBox<String> jcomboMarca;
    private javax.swing.JTextArea jtextAreaRecibo;
    private javax.swing.JTextField jtextDescuento;
    private javax.swing.JTextField jtextPrecio;
    // End of variables declaration//GEN-END:variables

    private void colocarInformacion() throws FileNotFoundException, IOException {
        File archivo = new File("src//modelos.txt");
        FileReader fr = new FileReader(archivo);
        BufferedReader br = new BufferedReader(fr);
        String linea;
        listaCarros = new ArrayList<Automovil>();
        while ((linea = br.readLine()) != null) {

            String[] datos = linea.split(";");
            int anio = Integer.parseInt(datos[2]);
            datos[3] = datos[3].substring(1);
            linea = datos[3];
            String[] precioTemp = linea.split("p");

            String precioTemp1 = precioTemp[0] + precioTemp[1] + precioTemp[2];
            precioTemp1 = precioTemp1.trim();
            int precio = Integer.parseInt(precioTemp1);

            listaCarros.add(new Automovil(datos[0], datos[1], anio, precio));

        }
        String cadena = "";
        String aux = "";
        for (int i = 0; i < listaCarros.size(); i++) {
            cadena = listaCarros.get(i).getMarca().toString();
            if (cadena == null ? aux != null : !cadena.equals(aux)) {
                jcomboMarca.addItem(cadena);
                aux = cadena;
            }
        }
         il = new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent ie) {
                if (ie.getSource() == jcomboMarca) {
                    rellenarAnio();
                    rellenarLinea();
                    rellenarPrecio();
                }
                if (ie.getSource() == jcomboLinea) {
                    rellenarAnio();
                    rellenarPrecio();
                }

            }
        };
        jcomboMarca.addItemListener(il);

    }

    private void rellenarLinea() {
        jcomboLinea.removeAllItems();
        for (int i = 0; i < listaCarros.size(); i++) {
            String seleccionado = (String) jcomboMarca.getSelectedItem();
            if (listaCarros.get(i).getMarca().equals(seleccionado)) {
                jcomboLinea.addItem(listaCarros.get(i).getLinea());

            }
        }
        jcomboLinea.addItemListener(il);
    }

    private void rellenarAnio() {
        jcomboAnio.removeAllItems();
        for (int i = 0; i < listaCarros.size(); i++) {
            String seleccionado = (String) jcomboLinea.getSelectedItem();
            if (listaCarros.get(i).getLinea().equals(seleccionado)) {
                jcomboAnio.addItem(String.valueOf(listaCarros.get(i).getAnio()));
            }
        }
    }

    private void rellenarPrecio() {

        for (int i = 0; i < listaCarros.size(); i++) {
            String seleccionado = (String) jcomboLinea.getSelectedItem();
                     
            String precio = objNF2.format(listaCarros.get(i).getPrecio());
            if (listaCarros.get(i).getLinea().equals(seleccionado)) {
                jtextPrecio.setText("$ " + precio);
            }
        }
    }
}
